FROM node:20-alpine
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY . .

RUN npm install pnpm -g && pnpm install --frozen-lockfile --ignore-scripts

EXPOSE 3000
CMD [ "npm", "run", "seed:run" ]
