export const MenuCode = {
  // User Management
  USER_MANAGEMENT: 'USER_MANAGEMENT',
  USER_OVERVIEW: 'USER_OVERVIEW',
  IDENTITY_ACCESS_MANAGEMENT: 'IDENTITY_ACCESS_MANAGEMENT',
  USER_GROUPS: 'USER_GROUPS',
  USER_DEPARTMENTS: 'USER_DEPARTMENTS',
  USER_PERIODS: 'USER_PERIODS',

  // Posts
  POST: 'POST',
  POSTS_OVERVIEW: 'POSTS_OVERVIEW',

  // Activities Management
  ACTIVITY_MANAGEMENT: 'ACTIVITY_MANAGEMENT',
  ACTIVITY_REQUESTS: 'ACTIVITY_REQUESTS',
  MY_ACTIVITY_REQUESTS: 'MY_ACTIVITY_REQUESTS',
  ACTIVITIES: 'ACTIVITIES',
  ACTIVITIES_LOGS: 'ACTIVITIES_LOGS',

  // Recruitment
  RECRUITMENT: 'RECRUITMENT',
  RECRUITMENT_OVERVIEW: 'RECRUITMENT_OVERVIEW',
};
