export enum SystemRoles {
  SUPER_ADMIN = 'Super Admin',
  HR = 'Human Resource',
  LEADER = 'Leader',
  MEDIA = 'Media',
  TRAINER = 'Trainer',
  MEMBER = 'Member',
}

/**
 * Permission should follow pattern:
 * {action}_{resource}
 */
export enum Permissions {
  /**
   * @description This is the super admin permission, system bypass all permission check
   */
  OWNER = 'OWNER',
  READ_USERS = 'READ_USERS',
  WRITE_USERS = 'WRITE_USERS',
  READ_IAM = 'READ_IAM',
  EDIT_IAM = 'EDIT_IAM',
  READ_ACTIVITY_REQUESTS = 'READ_ACTIVITY_REQUESTS',
  WRITE_ACTIVITY_REQUESTS = 'WRITE_ACTIVITY_REQUESTS',
  READ_MY_ACTIVITY_REQUESTS = 'READ_MY_ACTIVITY_REQUESTS',
  WRITE_MY_ACTIVITY_REQUESTS = 'WRITE_MY_ACTIVITY_REQUESTS',
  READ_ACTIVITIES = 'READ_ACTIVITIES',
  WRITE_ACTIVITIES = 'WRITE_ACTIVITIES',
  READ_ACTIVITY_LOGS = 'READ_ACTIVITY_LOGS',
  WRITE_ACTIVITY_LOGS = 'WRITE_ACTIVITY_LOGS',
  READ_FINGERPRINT_USERS = 'READ_FINGERPRINT_USERS',
  WRITE_FINGERPRINT_USERS = 'WRITE_FINGERPRINT_USERS',
  WRITE_PERIODS = 'WRITE_PERIODS',
  WRITE_DEPARTMENTS = 'WRITE_DEPARTMENTS',
  READ_PAYMENTS = 'READ_PAYMENTS',
  WRITE_PAYMENTS = 'WRITE_PAYMENTS',
  READ_KPI = 'READ_KPI',
}
