name: Build job

on:
  workflow_call:

jobs:
  setups:
    name: builder
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Setup packages
        run: pnpm install --frozen-lockfile

      - name: Build dist
        run: |
          pnpm build
