name: Unit test job

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  setups:
    name: unit-test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'pnpm'

      - name: Setup packages
        run: pnpm install --frozen-lockfile

      - name: Run lint check
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test:cov
          
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
