name: Unit test job

on:
  workflow_call:

jobs:
  setups:
    name: unit-test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/node_modules/
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            - cache-node-modules-

      - name: Run unit tests
        run: |
          pnpm test
